### ISSUE TITLE
Create third parties accounts

### ISSUE THREAD

**Issue by lutangar** [interpretable/api#4]
- [x] IPinfo
- [x] Sendgrid

**Comment by JeromeGutman** [comment]
cf carte https://github.com/interpretable/api/issues/1

**Comment by JeromeGutman** [comment]
Sengrid : I'm doing this task with @psibileau. We have to choose a double authentification method. With phone number if it's possible.
IPInfo : I'm asking to our developer team if the account will be general for erasme machines, or only for interpretable

**Comment by JeromeGutman** [comment]
IPInfo : the account has been created. Waiting for email validation from @psibileau

**Comment by JeromeGutman** [comment]
Sendgrid : the account has been created

**Comment by JeromeGutman** [comment]
IP info : the account has been created
